start python scripts\test_surrogate_strats.py -compute -ratio 0 -nruns 10 -problem 1 -agents 20 -token s5c -dimensions 5 -strategy 1 -sigma 0.2
start python scripts\test_surrogate_strats.py -compute -ratio 1 -nruns 10 -problem 1 -agents 20 -token s5c -dimensions 5 -strategy 1 -sigma 0.2
start python scripts\test_surrogate_strats.py -compute -ratio 2 -nruns 10 -problem 1 -agents 20 -token s5c -dimensions 5 -strategy 1 -sigma 0.2
start python scripts\test_surrogate_strats.py -compute -ratio 3 -nruns 10 -problem 1 -agents 20 -token s5c -dimensions 5 -strategy 1 -sigma 0.2
start python scripts\test_surrogate_strats.py -compute -ratio 4 -nruns 10 -problem 1 -agents 20 -token s5c -dimensions 5 -strategy 1 -sigma 0.2
start python scripts\test_surrogate_strats.py -compute -ratio 0 -nruns 10 -problem 1 -agents 20 -token s5d -dimensions 5 -strategy 1 -sigma 0.05
start python scripts\test_surrogate_strats.py -compute -ratio 1 -nruns 10 -problem 1 -agents 20 -token s5d -dimensions 5 -strategy 1 -sigma 0.05
start python scripts\test_surrogate_strats.py -compute -ratio 2 -nruns 10 -problem 1 -agents 20 -token s5d -dimensions 5 -strategy 1 -sigma 0.05
start python scripts\test_surrogate_strats.py -compute -ratio 3 -nruns 10 -problem 1 -agents 20 -token s5d -dimensions 5 -strategy 1 -sigma 0.05
start python scripts\test_surrogate_strats.py -compute -ratio 4 -nruns 10 -problem 1 -agents 20 -token s5d -dimensions 5 -strategy 1 -sigma 0.05
